# Generated by Django 4.1.1 on 2022-09-16 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.TextField(max_length=150, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('ticker', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('sector', models.CharField(max_length=150)),
                ('industry', models.CharField(max_length=150)),
                ('employees_count', models.TextField()),
                ('sic_no', models.TextField()),
                ('location', models.TextField()),
                ('exchange_id', models.TextField(max_length=150)),
                ('cik_no', models.TextField()),
                ('cusip', models.TextField()),
                ('currency_id', models.TextField(max_length=150)),
                ('data_source_id', models.TextField(max_length=150)),
                ('ckr_log', models.TextField(max_length=150)),
                ('similar_fund_log', models.TextField(max_length=150)),
                ('address', models.TextField(max_length=150)),
                ('company_name', models.TextField(max_length=150)),
                ('phone_no', models.TextField(max_length=150)),
                ('website', models.TextField(max_length=150)),
                ('is_Active', models.TextField(max_length=150)),
                ('url_slug', models.TextField(max_length=150)),
                ('delisted_date', models.DateField()),
                ('delisted_reason', models.TextField()),
                ('image_name', models.TextField()),
                ('image_aspect_ratio', models.TextField(max_length=150)),
                ('cumulative_return', models.DateTimeField(max_length=150)),
            ],
        ),
    ]
