# Generated by Django 4.1.1 on 2022-09-16 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0002_alter_value_address_alter_value_ckr_log_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='cik_no',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='cusip',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='delisted_date',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='delisted_reason',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='employees_count',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='image_name',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='location',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='sic_no',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
    ]
