# Generated by Django 4.1.1 on 2022-09-16 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0004_alter_value_cik_no_alter_value_ckr_log_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='end_date',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
    ]
