# Generated by Django 4.1.1 on 2022-09-16 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0005_alter_value_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Return',
            fields=[
                ('start_date', models.DateField()),
                ('returns', models.DecimalField(decimal_places=20, max_digits=20)),
                ('equity_id', models.CharField(max_length=6, primary_key=True, serialize=False)),
                ('open', models.DecimalField(decimal_places=20, max_digits=20)),
                ('high', models.DecimalField(decimal_places=20, max_digits=20)),
                ('low', models.DecimalField(decimal_places=20, max_digits=20)),
                ('close', models.DecimalField(decimal_places=20, max_digits=20)),
                ('adj_close', models.DecimalField(decimal_places=20, max_digits=20)),
            ],
        ),
    ]
