# Generated by Django 4.1.1 on 2022-09-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0006_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='adj_close',
            field=models.DecimalField(decimal_places=20, max_digits=2000),
        ),
        migrations.AlterField(
            model_name='return',
            name='close',
            field=models.DecimalField(decimal_places=20, max_digits=2000),
        ),
        migrations.AlterField(
            model_name='return',
            name='high',
            field=models.DecimalField(decimal_places=20, max_digits=2000),
        ),
        migrations.AlterField(
            model_name='return',
            name='low',
            field=models.DecimalField(decimal_places=20, max_digits=2000),
        ),
        migrations.AlterField(
            model_name='return',
            name='open',
            field=models.DecimalField(decimal_places=20, max_digits=2000),
        ),
    ]
