# Generated by Django 4.1.1 on 2022-09-16 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0008_alter_return_adj_close_alter_return_close_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='equity_id',
            field=models.AutoField(max_length=6, primary_key=True, serialize=False),
        ),
    ]
