# Generated by Django 4.1.1 on 2022-09-16 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0009_alter_return_equity_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Returns',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('returns', models.DecimalField(decimal_places=20, max_digits=20)),
                ('equity_id', models.CharField(max_length=6)),
                ('open', models.DecimalField(decimal_places=10, max_digits=19)),
                ('high', models.DecimalField(decimal_places=10, max_digits=19)),
                ('low', models.DecimalField(decimal_places=10, max_digits=19)),
                ('close', models.DecimalField(decimal_places=10, max_digits=19)),
                ('adj_close', models.DecimalField(decimal_places=10, max_digits=19)),
            ],
        ),
        migrations.DeleteModel(
            name='Return',
        ),
    ]
