# Generated by Django 4.1.1 on 2022-09-17 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0010_returns_delete_return'),
    ]

    operations = [
        migrations.AlterField(
            model_name='value',
            name='address',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='ckr_log',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='company_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='cumulative_return',
            field=models.DateTimeField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='currency_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='data_source_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='description',
            field=models.TextField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='exchange_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='image_aspect_ratio',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='industry',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='is_Active',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='phone_no',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='sector',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='similar_fund_log',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='start_date',
            field=models.DateField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='ticker',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='url_slug',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='value',
            name='website',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
