# Generated by Django 4.1.1 on 2022-09-18 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('values', '0012_alter_returns_adj_close_alter_returns_close_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='returns',
            old_name='start_date',
            new_name='date',
        ),
    ]
